name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: 3.8
            toxenv: py38
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
      - name: Running tox
        run: |
          tox -e ${{ matrix.toxenv }}

  codestyle:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: codestyle
        run: |
          tox -e codestyle
  CI:
    runs-on: ${{ matrix.os }}
    needs: build
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: 3.7
            toxenv: py37
          - os: windows-latest
            python-version: 3.7
            toxenv: py37
          - os: macos-latest
            python-version: 3.7
            toxenv: py37
          - os: ubuntu-latest
            python-version: 3.8
            toxenv: py38
          - os: windows-latest
            python-version: 3.8
            toxenv: py38
          - os: macos-latest
            python-version: 3.8
            toxenv: py38
          - os: ubuntu-latest
            python-version: 3.9
            toxenv: py39
          - os: windows-latest
            python-version: 3.9
            toxenv: py39
          - os: macos-latest
            python-version: 3.9
            toxenv: py39
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
      - name: Running tox
        run: |
          tox -e ${{ matrix.toxenv }}
